1702447807985	Sync.LogManager	DEBUG	Flushing file log
1702447808013	Sync.LogManager	DEBUG	Log cleanup threshold time: 1701583808013
1702447808028	Sync.LogManager	DEBUG	Done deleting files.
1702448307941	Sync.SyncScheduler	DEBUG	Woke from sleep.
1702448307943	Sync.SyncScheduler	DEBUG	Online, will sync in 2s.
1702448307943	Sync.SyncScheduler	DEBUG	Next sync in 2000 ms. (why=wake_notification)
1702448307944	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1702448309948	Sync.Service	DEBUG	User-Agent: Firefox/120.0.1 (Linux x86_64) FxSync/1.122.0.20231130105227.desktop
1702448309948	Sync.Service	INFO	Starting sync at 2023-12-13 09:18:29 in browser session 8WTrMFah8oWB
1702448309948	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1702448309951	Sync.Status	INFO	Resetting Status.
1702448309951	Sync.Status	DEBUG	Status.service: error.sync.failed => success.status_ok
1702448309952	FirefoxAccounts	DEBUG	FxAccountsProfileClient: Requested profile
1702448309952	FirefoxAccounts	DEBUG	getOAuthToken enter
1702448309953	FirefoxAccounts	TRACE	getCachedToken returning cached token
1702448309953	FirefoxAccounts	DEBUG	getOAuthToken returning a cached token
1702448309953	Services.Common.RESTRequest	DEBUG	GET request to https://profile.accounts.firefox.com/v1/profile
1702448309955	Sync.SyncAuthManager	INFO	Getting sync key
1702448309955	Sync.SyncAuthManager	INFO	Getting a sync token from: https://token.services.mozilla.com/1.0/sync/1.5
1702448309955	Sync.SyncAuthManager	DEBUG	Getting a token using OAuth
1702448309955	FirefoxAccounts	DEBUG	getOAuthToken enter
1702448309955	FirefoxAccounts	TRACE	getCachedToken returning cached token
1702448309955	FirefoxAccounts	DEBUG	getOAuthToken returning a cached token
1702448309956	Services.Common.TokenServerClient	DEBUG	Beginning OAuth token exchange: https://token.services.mozilla.com/1.0/sync/1.5
1702448309956	Services.Common.RESTRequest	DEBUG	GET request to https://token.services.mozilla.com/1.0/sync/1.5
1702448309959	Services.Common.RESTRequest	DEBUG	GET https://profile.accounts.firefox.com/v1/profile failed: 2152398878 - NS_ERROR_UNKNOWN_HOST
1702448309960	FirefoxAccounts	ERROR	Background refresh of profile failed: {"name":"FxAccountsProfileClientError","code":null,"errno":998,"error":"NETWORK_ERROR","message":"[Exception... \"NS_ERROR_UNKNOWN_HOST\"  nsresult: \"0x804b001e (NS_ERROR_UNKNOWN_HOST)\"  location: \"JS frame :: resource://services-common/rest.sys.mjs :: onStopRequest :: line 479\"  data: no]"}
1702448309962	Services.Common.RESTRequest	DEBUG	GET https://token.services.mozilla.com/1.0/sync/1.5 failed: 2152398878 - NS_ERROR_UNKNOWN_HOST
1702448309962	Sync.SyncAuthManager	ERROR	Non-authentication error in _fetchTokenForUser: TokenServerClientNetworkError({"error":{}})(resource://services-common/tokenserverclient.sys.mjs:28:36) JS Stack trace: TokenServerClientNetworkError@tokenserverclient.sys.mjs:51:16
_tokenServerExchangeRequest@tokenserverclient.sys.mjs:235:13
1702448309963	Sync.Status	DEBUG	Status.login: success.login => error.login.reason.network
1702448309963	Sync.Status	DEBUG	Status.service: success.status_ok => error.login.failed
1702448309963	Sync.SyncAuthManager	ERROR	Failed to fetch a token for authentication: TokenServerClientNetworkError({"error":{}})(resource://services-common/tokenserverclient.sys.mjs:28:36) JS Stack trace: TokenServerClientNetworkError@tokenserverclient.sys.mjs:51:16
_tokenServerExchangeRequest@tokenserverclient.sys.mjs:235:13
1702448309965	FirefoxAccounts	TRACE	not checking freshness of profile as it remains recent
1702448309969	Sync.Resource	WARN	GET request to https://sync-1-us-west1-g.sync.services.mozilla.com/1.5/210363591/info/collections failed: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1702448309969	Sync.Status	DEBUG	Status.sync: success.sync => error.login.reason.network
1702448309969	Sync.Status	DEBUG	Status.service: error.login.failed => error.sync.failed
1702448309970	Sync.ErrorHandler	ERROR	Sync encountered an error: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1702448309970	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=reschedule)
1702448309971	Sync.Telemetry	INFO	Early submission of sync telemetry due to changed IDs/NodeType
1702448309976	Sync.Service	DEBUG	Exception calling anonymous function: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
